CREATE TABLE users(
   USERID INT PRIMARY KEY NOT NULL,
   NAME TEXT NOT NULL
);
CREATE TABLE movies(
   MOVIEID INT PRIMARY KEY NOT NULL,
   TITLE TEXT NOT NULL
);
CREATE TABLE taginfo(
   TAGID INT PRIMARY KEY NOT NULL,
   CONTENT TEXT NOT NULL
);
CREATE TABLE genres(
   GENREID INT PRIMARY KEY NOT NULL,
   NAME TEXT NOT NULL
);
CREATE TABLE ratings(
   USERID INT REFERENCES USERS(USERID),
   MOVIEID INT REFERENCES MOVIES(MOVIEID),
   RATING NUMERIC NOT NULL CHECK(RATING>=0 AND RATING<=5),
   TIMESTAMP BIGINT NOT NULL,
   PRIMARY KEY (USERID, MOVIEID)
);
CREATE TABLE tags(
   USERID INT REFERENCES USERS(USERID),
   MOVIEID INT REFERENCES MOVIES(MOVIEID),
   TAGID INT REFERENCES TAGINFO(TAGID),
   TIMESTAMP BIGINT NOT NULL,
   PRIMARY KEY (USERID, MOVIEID, TAGID)
);
CREATE TABLE HASAGENRE(
   MOVIEID INT REFERENCES MOVIES(MOVIEID),
   GENREID INT REFERENCES GENRES(GENREID),
   PRIMARY KEY (MOVIEID, GENREID)   
);